import { ChevronDown, Pause, Plus, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { api } from "../lib/api";
import type { Exercise, ExerciseRecommendations, MeasurementType, RecommendationItem } from "../lib/types";
import { ExerciseEditor } from "./ExerciseEditor";
import { ExerciseImage } from "./ExerciseImage";
import { Modal } from "./Modal";

interface Props { day: string; presentIds: number[]; onChoose: (exercise: Exercise) => void; onClose: () => void; }
type Sort = "recommended" | "muscle" | "exercise";
const elapsed = (days: number | null, label: string) => days === null ? "Never done" : `${label} ${days === 1 ? "1 day" : `${days} days`} ago`;

export function ExercisePicker({ day, presentIds, onChoose, onClose }: Props) {
  const [data, setData] = useState<ExerciseRecommendations | null>(null);
  const [query, setQuery] = useState(""); const [measurementType, setMeasurementType] = useState<"" | MeasurementType>("");
  const [muscleGroup, setMuscleGroup] = useState(""); const [muscleRole, setMuscleRole] = useState("any");
  const [sort, setSort] = useState<Sort>("recommended"); const [includePaused, setIncludePaused] = useState(false);
  const [neverOpen, setNeverOpen] = useState(false); const [creating, setCreating] = useState(false);
  const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const options = useMemo(
    () => ({ query, measurementType, muscleGroup, muscleRole, includePaused, sort }),
    [query, measurementType, muscleGroup, muscleRole, includePaused, sort],
  );

  useEffect(() => { let active = true; setError(""); api.exerciseRecommendations(day, options).then((items) => { if (active) { setData(items); if (query) setNeverOpen(true); } }).catch((caught) => active && setError(caught instanceof Error ? caught.message : "Could not load recommendations.")); return () => { active = false; }; }, [day, options, query]);
  async function pause(item: RecommendationItem, period: "week" | "month" | "six_months" | "year" | "forever" | "resume") { try { await api.updateRecommendationPause(item.exercise.id, period); setNotice(period === "resume" ? `${item.exercise.name} resumed.` : `${item.exercise.name} paused from recommendations.`); setData(await api.exerciseRecommendations(day, options)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not update recommendation pause."); } }
  function choose(item: RecommendationItem) { if (presentIds.includes(item.exercise.id)) { setNotice(`${item.exercise.name} is already added to this day.`); return; } onChoose(item.exercise); }
  function result(item: RecommendationItem) { const alreadyAdded = presentIds.includes(item.exercise.id); return <article className="exercise-result-row" key={item.exercise.id}><button className="exercise-result" disabled={alreadyAdded} onClick={() => choose(item)}><ExerciseImage imageKey={item.exercise.imageKey} name={item.exercise.name} /><span><strong>{item.exercise.name}</strong><small>{alreadyAdded ? "Already added" : `${elapsed(item.daysSinceLastDone, "Last done")} · ${item.exercise.primaryMuscle?.replaceAll("_", " ") ?? "Muscles not set"}`}</small></span></button><details className="pause-menu"><summary aria-label={`Pause recommendations for ${item.exercise.name}`}><Pause /></summary><div>{item.paused ? <button onClick={() => void pause(item, "resume")}>Resume recommendations</button> : <><span>Pause recommendations</span><button onClick={() => void pause(item, "week")}>1 week</button><button onClick={() => void pause(item, "month")}>1 month</button><button onClick={() => void pause(item, "six_months")}>6 months</button><button onClick={() => void pause(item, "year")}>1 year</button><button onClick={() => void pause(item, "forever")}>Indefinitely</button></>}</div></details></article>; }
  const hasResults = Boolean(data?.allExercises.length);
  if (creating) return <Modal title="New exercise" onClose={() => setCreating(false)} wide><ExerciseEditor onCancel={() => setCreating(false)} onSaved={(exercise) => onChoose(exercise)} /></Modal>;
  return <Modal title="Add exercise" onClose={onClose} wide><div className="picker-toolbar"><label className="search-box"><Search /><span className="sr-only">Search exercises</span><input type="search" placeholder="Search exercises" value={query} onChange={(event) => setQuery(event.target.value)} autoFocus /></label><button className="primary" onClick={() => setCreating(true)}><Plus />New exercise</button></div><div className="picker-filters"><label>View<select value={sort} onChange={(event) => setSort(event.target.value as Sort)}><option value="recommended">Recommended</option><option value="muscle">Muscle A–Z</option><option value="exercise">Exercise A–Z</option></select></label><label>Muscle<select value={muscleGroup} onChange={(event) => setMuscleGroup(event.target.value)}><option value="">All muscles</option>{data?.muscleGroups.map((group) => <option key={group.slug} value={group.slug}>{group.name}</option>)}</select></label><label>Role<select value={muscleRole} onChange={(event) => setMuscleRole(event.target.value)}><option value="any">Any target</option><option value="primary">Primary</option><option value="secondary">Secondary</option></select></label><label>Type<select value={measurementType} onChange={(event) => setMeasurementType(event.target.value as "" | MeasurementType)}><option value="">All types</option><option value="repetitions">Repetitions</option><option value="duration">Duration</option><option value="timed_repetitions">Timed repetitions</option></select></label><label className="checkbox-row"><input type="checkbox" checked={includePaused} onChange={(event) => setIncludePaused(event.target.checked)} />Show paused</label></div>{notice && <p className="notice" role="status">{notice}</p>}{error && <p className="error" role="alert">{error}</p>}<div className="exercise-results">{sort === "exercise" ? data?.allExercises.map(result) : <>{data?.groups.map((group) => <section className="recommendation-group" key={group.muscle}><h3>{group.muscleName}<small>{elapsed(group.daysSinceLastTrained, "Last trained")}</small></h3>{group.exercises.map(result)}</section>)}{data?.unclassified.length ? <section className="recommendation-group"><h3>Muscles not set</h3>{data.unclassified.map(result)}</section> : null}</>}{data && sort !== "exercise" && data.neverTried.length > 0 && <section className="never-tried"><button className="never-tried-toggle" onClick={() => setNeverOpen(!neverOpen)} aria-expanded={neverOpen}>Never tried ({data.neverTried.length}) <ChevronDown className={neverOpen ? "rotated" : ""} /></button>{neverOpen && data.neverTried.map(result)}</section>}{!error && data && !hasResults && <p className="empty-copy">No matching exercises.</p>}</div></Modal>;
}
