import { Beef, MoreHorizontal, Pencil, Plus, Ruler, Trash2, Weight } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { api } from "../lib/api";
import type { BodyMeasurement, BodyMeasurementPayload, Profile } from "../lib/types";

type Metric = "weightKg" | "waistCm";
const empty = (date: string, metric?: Metric): BodyMeasurementPayload => ({ date, weightKg: metric === "weightKg" ? "" : null, waistCm: metric === "waistCm" ? "" : null });

function Trend({ title, values, unit }: { title: string; values: BodyMeasurement[]; unit: string }) {
  const points = values.map((item) => Number(unit === "kg" ? item.weightKg : item.waistCm)).filter(Number.isFinite).reverse();
  if (points.length < 2) return <div className="trend-card"><h3>{title}</h3><small>{points.length ? "Add one more reading to see your trend." : "Add a reading to start your trend."}</small></div>;
  const min = Math.min(...points); const max = Math.max(...points); const spread = max - min || 1;
  const line = points.map((point, index) => `${index * 100 / (points.length - 1)},${76 - ((point - min) / spread) * 62}`).join(" ");
  return <div className="trend-card"><h3>{title}</h3><small>{points[points.length - 1]} {unit} latest</small><svg className="trend-line" viewBox="0 0 100 90" preserveAspectRatio="none" aria-label={`${title} trend`} role="img"><polyline fill="none" stroke="currentColor" strokeWidth="3" points={line} /></svg></div>;
}

export function MeasurementsPage({ today }: { today: string }) {
  const [profile, setProfile] = useState<Profile | null>(null); const [measurements, setMeasurements] = useState<BodyMeasurement[]>([]);
  const [draft, setDraft] = useState<BodyMeasurementPayload>(empty(today)); const [metric, setMetric] = useState<Metric | null>(null); const [editing, setEditing] = useState<number | null>(null);
  const [editProfile, setEditProfile] = useState(false); const [menu, setMenu] = useState(false); const [heightCm, setHeightCm] = useState(""); const [dateOfBirth, setDateOfBirth] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const [nextProfile, nextMeasurements] = await Promise.all([api.profile(), api.bodyMeasurements()]); setProfile(nextProfile); setMeasurements(nextMeasurements); setHeightCm(nextProfile.heightCm ?? ""); setDateOfBirth(nextProfile.dateOfBirth ?? ""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load measurements."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function saveMeasurement() { setSaving(true); setError(""); try { if (editing === null) await api.createBodyMeasurement(draft); else await api.updateBodyMeasurement(editing, draft); setMetric(null); setEditing(null); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not save measurement."); } finally { setSaving(false); } }
  async function saveProfile() { setSaving(true); setError(""); try { setProfile(await api.updateProfile({ heightCm: heightCm || null, dateOfBirth: dateOfBirth || null })); setEditProfile(false); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not save profile."); } finally { setSaving(false); } }
  const latestWeight = measurements.find((item) => item.weightKg !== null)?.weightKg; const latestWaist = measurements.find((item) => item.waistCm !== null)?.waistCm;
  const updateMetric = (next: Metric) => { setEditing(null); setMetric(next); setDraft(empty(today, next)); };
  const editHistory = (item: BodyMeasurement) => { setEditing(item.id); setMetric(null); setDraft({ date: item.date, weightKg: item.weightKg, waistCm: item.waistCm }); };
  const profileInfo = `${profile?.heightCm ? `${profile.heightCm} cm` : "Not set"}`;
  return <main className="page measurements-page"><header className="section-title"><h1>Measurements</h1><p>Track body changes over time.</p></header>{error && <p className="error-panel" role="alert">{error}</p>}
    <section className="settings-card"><h2>Latest</h2><div className="measurement-summary"><div className="metric"><Weight /><span>Weight</span><strong>{latestWeight ? `${latestWeight} kg` : "—"}</strong><button className="secondary metric-update" onClick={() => updateMetric("weightKg")}><Plus />Update</button></div><div className="metric"><Ruler /><span>Waist</span><strong>{latestWaist ? `${latestWaist} cm` : "—"}</strong><button className="secondary metric-update" onClick={() => updateMetric("waistCm")}><Plus />Update</button></div></div><div className="trend-grid"><Trend title="Weight" values={measurements.filter((item) => item.weightKg)} unit="kg" /><Trend title="Waist" values={measurements.filter((item) => item.waistCm)} unit="cm" /></div>{(metric || editing !== null) && <div className="measurement-form"><h3>{editing !== null ? "Edit measurement" : `Update ${metric === "weightKg" ? "weight" : "waist"}`}</h3><div className="form-grid"><label>Date<input type="date" max={today} value={draft.date} onChange={(event) => setDraft({ ...draft, date: event.target.value })} /></label>{(metric === "weightKg" || editing !== null) && <label>Weight <span className="optional">kg</span><input inputMode="decimal" value={draft.weightKg ?? ""} onChange={(event) => setDraft({ ...draft, weightKg: event.target.value || null })} /></label>}{(metric === "waistCm" || editing !== null) && <label>Waist <span className="optional">cm</span><input inputMode="decimal" value={draft.waistCm ?? ""} onChange={(event) => setDraft({ ...draft, waistCm: event.target.value || null })} /></label>}</div><div className="draft-actions"><button onClick={() => { setMetric(null); setEditing(null); }}>Cancel</button><button className="primary" disabled={saving} onClick={() => void saveMeasurement()}>Save</button></div></div>}</section>
    <section className="settings-card"><div className="card-heading profile-heading"><div><h2>Profile</h2>{!editProfile && <div className="profile-values"><p><Ruler /><span>Height</span><strong>{profileInfo}</strong></p><p><Beef /><span>Age</span><strong>{profile?.age ?? "Not set"}{profile?.age !== null && profile?.age !== undefined ? " years" : ""}</strong></p></div>}</div><div className="profile-menu"><button className="icon-button" aria-label="Profile options" onClick={() => setMenu(!menu)}><MoreHorizontal /></button>{menu && <button className="profile-menu-action" onClick={() => { setEditProfile(true); setMenu(false); }}><Pencil />Edit profile</button>}</div></div>{editProfile && <div className="profile-form"><div className="form-grid"><label>Height <span className="optional">cm</span><input inputMode="decimal" value={heightCm} onChange={(event) => setHeightCm(event.target.value)} /></label><label>Date of birth<input type="date" max={today} value={dateOfBirth} onChange={(event) => setDateOfBirth(event.target.value)} /></label></div><div className="draft-actions"><button onClick={() => setEditProfile(false)}>Cancel</button><button className="primary" disabled={saving} onClick={() => void saveProfile()}>Save profile</button></div></div>}</section>
    <section className="settings-card"><h2>History</h2>{measurements.length === 0 ? <p className="empty-copy">No measurements yet.</p> : <div className="measurement-history">{measurements.map((item) => <div className="measurement-row" key={item.id}><div><strong>{item.date}</strong><p>{[item.weightKg && `${item.weightKg} kg`, item.waistCm && `${item.waistCm} cm waist`].filter(Boolean).join(" · ")}</p></div><div className="row-actions"><button className="icon-button" aria-label={`Edit measurement from ${item.date}`} onClick={() => editHistory(item)}><Pencil /></button><button className="icon-button danger" aria-label={`Delete measurement from ${item.date}`} onClick={async () => { if (!window.confirm("Delete this measurement?")) return; try { await api.deleteBodyMeasurement(item.id); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not delete measurement."); } }}><Trash2 /></button></div></div>)}</div>}</section></main>;
}
